### ISSUE TITLE
fscrawler container is unhealthy.

### ISSUE THREAD

**Issue by jelinekb** [shadiakiki1986/docker-fscrawler#10]
When starting **docker-compose.yml**, I receive the follow errors:
```
ERROR: for fscrawler  Container "b18510f6b3cd" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
Running **docker inspect --format='{{json .State.Health}}' <container>** yields:
`{"Status":"unhealthy","FailingStreak":3,"Log":[{"Start":"2018-11-24T14:29:57.31355179-06:00","End":"2018-11-24T14:29:57.395705557-06:00","ExitCode":126,"Output":"/usr/local/bin/docker-healthcheck: /usr/local/bin/docker-healthcheck: is a directory\n"},{"Start":"2018-11-24T14:30:27.408426387-06:00","End":"2018-11-24T14:30:27.48572124-06:00","ExitCode":126,"Output":"/usr/local/bin/docker-healthcheck: /usr/local/bin/docker-healthcheck: is a directory\n"},{"Start":"2018-11-24T14:30:57.497604654-06:00","End":"2018-11-24T14:30:57.575523908-06:00","ExitCode":126,"Output":"/usr/local/bin/docker-healthcheck: /usr/local/bin/docker-healthcheck: is a directory\n"}]}

Running the healthcheck from within the container (`docker exec -it <container name> /bin/bash /usr/local/bin/docker-healthcheck`) gives the following error:
```
/bin/bash: /usr/local/bin/docker-healthcheck: No such file or directory
```

fscrawler appears to work upon disabling the “docker-compose.yml” healthcheck. It appears that the healthcheck script is not being properly copied into container since /usr/local/bin/docker-healthcheck is an empty folder (i.e., is not a script)).

**Comment by shadiakiki1986** [comment]
Hi. I'm currently travelling AFK and will be back in a few days. Will reply
when I'm back

**Comment by jelinekb** [comment]
I noticed the docker-compose file is copying docker-healthcheck from ./docker-healthcheck (i.e., ./docker-healthcheck:/usr/local/bin/docker-healthcheck). I believe the issue was caused by my mistake in your directions below. I cloned your project folder, which has the docker-healthcheck file in build/elasticsearch/docker-healthcheck (rather than ./docker-healthcheck).

Original instructions:

> Download the following files from this git repository. Cloning the whole repository is not necessary.
> docker-compose-deployment.yml
> build/elasticsearch/docker-healthcheck
> 
> **Make a new empty folder and put these two files in it.** This directory will be the home of your configurations, and the location from which you can control your containers and make changes.
>
