### ISSUE TITLE
Expose the Rest API Port 8080 Outside Container

### ISSUE THREAD

**Issue by suresh-nataraj** [shadiakiki1986/docker-fscrawler#6]
Hi All,

It would be good help to expose the rest API port outside Container . SO we can use that to index files from other hosts.

Thanks,
Suresh

**Comment by shadiakiki1986** [comment]
That's a great idea. Feel free to submit a pull request for it, and I'll be happy to merge.

**Comment by suresh-nataraj** [comment]
I dont think any changes required in the Dockerfile . We can publish the port using -p option according to docker Documentation . But thats not happening with scrawler docker .

I am using the below command and fscrawler starting the Rest Service in 0.0.0.0:8080 . I tried with 127.0.0.1 ,which is default . When the container is running , I am not able to see PORTS also in docker ps .



```
docker run -it --rm -p 8080:8080 \
  --net="host" \
  --name my-fscrawler \
  -v $PWD/test/data/:/usr/share/fscrawler/data/:ro \
  -v $PWD/config:/usr/share/fscrawler/config/ \
  shadiakiki1986/fscrawler --username elastic --config_dir /usr/share/fscrawler/config/ --rest --loop 0 --debug --trace archivejob
```

```
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                              NAMES

009496a56c18        shadiakiki1986/fscrawler                              "/entry.sh --usern..."   4 minutes ago       Up 4 minutes                                           my-fscrawler

f5eb7876bb6c        docker.elastic.co/elasticsearch/elasticsearch:5.1.2   "/bin/bash bin/es-..."   11 minutes ago      Up 11 minutes       0.0.0.0:9200->9200/tcp, 9300/tcp   elasticsearchdocker_elastics
```

Could you please let me know whether that works for you ? I am stuck with this for last two days . Please suggest me any working solution also .

**Comment by shadiakiki1986** [comment]
Yes I already do that. Check [here](https://github.com/teamshadi/docker-sic-namecheck/blob/master/docker-compose.yml#L97) for an example and let me know if it helps you

**Comment by shadiakiki1986** [comment]
Hey @suresh-nataraj did this work out for you?

**Comment by suresh-nataraj** [comment]
Hi @shadiakiki1986 I just exposed 8080 and it worked like charm .
