### ISSUE TITLE
Documentation is incorrect about docker communication and run options

### ISSUE THREAD

**Issue by Trevortds** [shadiakiki1986/docker-fscrawler#8]
> the default config depends on having a running elasticsearch instance on the localhost at port 9200. Start one with:

This is incorrect. Docker containers can't talk to localhost, ever. Containers can only see other containers if they are networked by the docker service. "localhost" is meaningless for docker containers. It seems the author has done tests only within the context of docker-compose, which implicitly networks containers in the same compose file. 

As it stands, that means that copying the author's docker-compose file and editing the sources and environment and adding the docker healthcheck thing to the elastic image is the *only* way to run docker-fscrawler.

**Comment by shadiakiki1986** [comment]
How do you suggest this be improved?

**Comment by Trevortds** [comment]
Well, my first instinct was to try to make it stand alone as the documentation says, but the experimentation I've done in the last hour suggests that may just be too hard to do. It might be easier just to cut that stuff out of the readme, and post a ready-to-go docker-compose.yml to go with the project, call it `docker-compose-deployment.yml` or something and tell users to just run it from that. 

I can make a PR if you prefer.

**Comment by shadiakiki1986** [comment]
Sure go ahead!
